name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust to your desired Node.js version

      - name: Install app dependencies
        run: npm install
        working-directory: ./client  # If your React app is in a 'client' subdirectory

      - name: Build React app
        run: npm run build
        working-directory: ./client

      - name: Install backend app dependencies
        run: npm install
        working-directory: ./server

      - name: Use the secret and update .env
        run: |
          echo "MONGO_URL=mongodb+srv://task_user:12345@hk.mtzsyle.mongodb.net/?retryWrites=true&w=majority" > .env
          echo "jwtSecret=123" > .env

      - name: Start the server
        run: npm start
        working-directory: ./server

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Task-mern-app
        uses: azure/webapps-deploy@v2
        with:
          app-name: Task-mern-app  # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_551C905AA7634D2D80179D2E4931A9FC }}
          package: .
